#!/usr/bin/env python3
"""Executable shim for the local agent-runner CLI."""

import os
import sys


CHECKOUT_DIR = os.path.dirname(os.path.realpath(__file__))
sys.path.insert(0, CHECKOUT_DIR)

from agent_runner.cli import main


if __name__ == "__main__":
    raise SystemExit(main())
